import { getReportDownloadUrl } from "../api/client";
import { formatBytes, formatDate } from "../data";
import { Button, Icon, PageHeader, Panel, RunStatusBadge } from "../design/ui";
import type { PageProps } from "./page-props";

function reportActionLabel(report: PageProps["reports"][number]): string {
  const kind = report.kind.trim();
  return kind === "" ? "Report" : kind.toUpperCase();
}

function isPdfReport(report: PageProps["reports"][number]): boolean {
  return report.kind.toLowerCase() === "pdf" || report.mimeType === "application/pdf";
}

export function ReportsPage({ reports, scans, navigate }: PageProps) {
  return (
    <div className="content-inner fadein">
      <PageHeader
        actions={<Button icon="scan-search" onClick={() => navigate({ page: "new-scan" })} variant="primary">Run Scan</Button>}
        icon="file-text"
        subtitle="Report artifacts generated by the local instance."
        title="Reports"
      />
      <Panel title="Report artifacts" subtitle="CSV export is not part of the MVP.">
        <div className="table-wrap">
          <table className="table">
            <thead>
              <tr>
                <th>Report</th>
                <th>Project</th>
                <th>Scan</th>
                <th>Status</th>
                <th className="num">Size</th>
                <th>Created</th>
                <th className="num">Action</th>
              </tr>
            </thead>
            <tbody>
              {reports.map((report) => {
                const scan = scans.find((candidate) => candidate.id === report.scanRunId);
                const actionLabel = reportActionLabel(report);
                const isDownloadablePdf = report.status === "ready" && isPdfReport(report);
                const downloadUrl = isDownloadablePdf ? getReportDownloadUrl(report.id) : null;
                return (
                  <tr key={report.id}>
                    <td>
                      <strong>{report.kind.toUpperCase()} accessibility report</strong>
                      <div className="table-sub mono">{report.artifactKey}</div>
                    </td>
                    <td>{report.projectName}</td>
                    <td className="mono">{report.scanRunId}</td>
                    <td>{report.status === "ready" && scan !== undefined ? <RunStatusBadge status="completed" /> : <span className="badge run queued"><Icon name="loader" size={11} className="spin" />Generating</span>}</td>
                    <td className="num">{formatBytes(report.sizeBytes)}</td>
                    <td>{formatDate(report.createdAt)}</td>
                    <td className="num">
                      {downloadUrl === null ? (
                        <Button disabled icon="download" size="sm" title={isDownloadablePdf ? "PDF download requires a configured API server" : report.status === "ready" ? `${actionLabel} download is not available in the web UI` : `${actionLabel} report is still generating`}>{actionLabel}</Button>
                      ) : (
                        <a className="btn default sm" download href={downloadUrl} title="Download PDF report">
                          <Icon name="download" size={13} />
                          {actionLabel}
                        </a>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </Panel>
    </div>
  );
}
